<?php

namespace App\Http\Requests;

class UserIdRequest extends ApiFormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function validationData(): array
    {
       return array_merge(parent::validationData(), $this->route()->parameters()); // TODO: Change the autogenerated stub
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'user_id' => "integer|exists:App\Models\User,id"
        ];
    }

    public function messages()
    {
        return [
            'user_id.integer' =>  "The user_id must be an integer.",
            'user_id.exists' =>  "User not found"
        ];
    }


}
